name: Test CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy ${{ github.ref_name }} to AWS
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 🟢 Setup Yarn
        run: yarn set version 4.4.0

      - name: Check Yarn version
        run: yarn -v

      - name: Echo Branch Name
        run: echo $BRANCH_NAME

      - name: 🏷 Create and push new build tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch --tags

          LAST_TAG=$(git tag --list "build-*" | sort -V | tail -n 1)

          if [[ "$LAST_TAG" =~ build-([0-9]+) ]]; then
            NEXT_NUM=$((BASH_REMATCH[1] + 1))
          else
            NEXT_NUM=1
          fi

          NEW_TAG="build-$NEXT_NUM"

          echo "Creating new tag: $NEW_TAG"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
